apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-pvc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debug-env
  template:
    metadata:
      labels:
        app: debug-env
    spec:
      containers:
      - name: debug-server
        image: hwchiu/netutils
        volumeMounts:
        - mountPath: /test
          name: test-nfs
      volumes:
      - name: test-nfs
        persistentVolumeClaim:
          claimName: pvc-nfs
