name: 2022_5_28_testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run: sudo apt-get install -f yamllint shellcheck

    - name: Run shell check
      run: |
        pushd cicd/application
        make shellcheck
        popd

    - name: Run shell check
      run: |
        pushd cicd/application
        make docker-lint
        popd

    - name: Run shell check
      run: |
        pushd cicd/application
        make yaml-lint
        popd
  test-k8s-minikube:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2

    - name: Install minikube
      run: |
        curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/v1.22.0-beta.0/minikube-linux-amd64
        chmod +x minikube
        sudo mv ./minikube /usr/local/bin

    - uses: azure/setup-kubectl@v1
    - name: Install kubernetes
      run:
        minikube start --driver=docker

    - name: Install bats
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core/
        sudo ./install.sh /usr/local

    - name: Deploy k8s Yaml
      run: |
        pushd cicd/application
        kubectl apply -f yamls
        popd

    - name: Wait Nginx Deployment
      run: |
       WAIT_TIME=0 ;until [ $WAIT_TIME -eq 24 ] || [ "3" = "$(kubectl get deployment nginx -ojsonpath='{.status.readyReplicas}')" ]; do echo "sleep ${WAIT_TIME}"; sleep 5; WAIT_TIME=$((WAIT_TIME+1)); done

    - name: Run Bats
      run: |
        pushd cicd/application
        make TYPE=minikube k8s-test
        popd

  test-k8s-kind:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2

    - name: Install KIND
      run: |
        curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64"
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin

    - uses: azure/setup-kubectl@v1

    - name: Install kubernetes
      run: |
        sudo kind create cluster --config vagrant/kind.yaml
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
    - name: Install bats
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core/
        sudo ./install.sh /usr/local

    - name: Deploy k8s Yaml
      run: |
        pushd cicd/application
        kubectl apply -f yamls
        popd

    - name: Wait Nginx Deployment
      run: ｜
      WAIT_TIME=0 ;until [ $WAIT_TIME -eq 24 ] || [ "3" = "$(kubectl get deployment nginx -ojsonpath='{.status.readyReplicas}')" ]; do echo "sleep ${WAIT_TIME}"; sleep 5; WAIT_TIME=$((WAIT_TIME+1)); done

    - name: Run Bats
      run: |
        pushd cicd/application
        make k8s-test
        popd
